#**Numpy Assignment**

1. Import NumPy Library as np


In [1]:
import numpy as np

2. Create an array of integers starting from 15 to 40 and store it in a variable called array1



In [ ]:
array1 = np.arange(15,40)
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

2.1. Create a second array of integers starting from 10 until 25 and store it in a variable called array2


In [ ]:
array2 = np.random.randint(10,25)
array2

24

2.2. What is the difference between the two arrays?


In [ ]:
# I used np.arange() to generate the first array, so the difference was that the arange function
# created a list, while the randint function only got one value randomly generated.

3. Create an array of all even integers from 2 to 20 and name it even_aaray1


In [ ]:
even_array1 = np.arange(2,20,2)
even_array1.shape

(9,)

3.1. Create an array of all even integers from 34 to 42 and name it even_array2


In [ ]:
even_array2 = np.arange(34,42,2)
even_array2.shape

(4,)

3.2. Create a matrix of the two arrays using the stack function


In [ ]:
matrix = np.stack((even_array1, even_array2), axis=1)
matrix

4. Create a 6×6 matrix with values ranging from 0 to 36 and retrieve the intersection of the 3rd row and 2nd column


In [2]:
matrix_6x6 = np.arange(36).reshape(6,6)
print(matrix_6x6)
matrix_intersec = matrix_6x6[3,2]
print('\n',matrix_intersec)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

 20


4.1. Create a 5×2 matrix from a standard normal distribution generated with python.


In [ ]:
matrix_5x2 = np.random.randn(5,2)
matrix_5x2

array([[ 0.07503153,  0.03667712],
       [-0.98951186, -0.70877924],
       [ 0.38574835,  1.17211463],
       [ 0.29765197, -0.8741465 ],
       [-1.37969587, -1.6941432 ]])

4.2. Retrieve the value intersecting the last row and the last column of your matrix


In [ ]:
matrix_5x2[-1,-1]

-1.6941431956144786

5. Using your matrix created at 4.1, calculate the following:


---


   a. minimum of the matrix



In [ ]:
np.amin(matrix_5x2)

-1.6941431956144786


---


   b. maximum of the matrix



In [ ]:
np.amax(matrix_5x2)

1.1721146284020412


---


   c. standard deviation of the matrix



In [ ]:
np.std(matrix_5x2)

0.8534634543123727


---


  d. variance of the matrix



In [ ]:
matrix_5x2.var()

0.7283998678468074


---

  e. mean of the matrix

In [ ]:
matrix_5x2.mean()

-0.3679053064197455